defmodule AdventOfCode2024.Day8Test do
  use ExUnit.Case

  @input """
  ............
  ........0...
  .....0......
  .......0....
  ....0.......
  ......A.....
  ............
  ............
  ........A...
  .........A..
  ............
  ............
  """

  test "part 1" do
    assert AdventOfCode2024.Day8.solve(@input, part: 1) == 14
  end

  test "part 2" do
    assert AdventOfCode2024.Day8.solve(@input, part: 2) == 34
  end
end
